"""empty message

Revision ID: f9baef076ed0
Revises: 
Create Date: 2025-04-13 00:13:43.999592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9baef076ed0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('has_specialties', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('medical_center',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('historial_clinico', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.Column('id_doctor', sa.Integer(), nullable=False),
    sa.Column('id_center', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Time(), nullable=False),
    sa.Column('id_specialty', sa.Integer(), nullable=False),
    sa.Column('confirmation', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_center'], ['medical_center.id'], ),
    sa.ForeignKeyConstraint(['id_doctor'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['id_patient'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['id_specialty'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_center_doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_medical_center', sa.Integer(), nullable=False),
    sa.Column('id_doctor', sa.Integer(), nullable=False),
    sa.Column('office', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_doctor'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['id_medical_center'], ['medical_center.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_doctor', sa.Integer(), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id_center', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_center'], ['medical_center.id'], ),
    sa.ForeignKeyConstraint(['id_doctor'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['id_patient'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialties_doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_specialty', sa.Integer(), nullable=False),
    sa.Column('id_doctor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_doctor'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['id_specialty'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialties_doctor')
    op.drop_table('review')
    op.drop_table('medical_center_doctor')
    op.drop_table('appointment')
    op.drop_table('user')
    op.drop_table('specialties')
    op.drop_table('patient')
    op.drop_table('medical_center')
    op.drop_table('doctors')
    # ### end Alembic commands ###
